idf_component_register(
    SRCS
        "app_main.c"
        "audio_es8311.c"
        "lcd_driver.c"
        "doubao_client.c"
        "command.c"
        "spiffs.c"
        "time_sync.c"
        "uart.c"
        "wifi_manager.c"
        "img_car_wifi.c"
        "img_car_stop.c"
        "img_car_forward.c"
        "img_car_backward.c"
        "img_car_left.c"
        "img_car_right.c"
        "img_car_patrol.c"
        "img_car_hand_up.c"
        "img_car_hand_down.c"
        "img_car_dance.c"
        "img_car_listen.c"
        "img_car_think.c"
        "img_car_talk.c"
    INCLUDE_DIRS
        "."
    PRIV_REQUIRES
        nvs_flash
        esp_wifi
        esp_netif
        esp_event
        esp_timer
        esp_driver_gpio
        esp_driver_spi
        esp_driver_i2c
        esp_driver_i2s
        esp_driver_uart
        esp_lcd
        spiffs
        esp_websocket_client
        esp-tls
        cjson
        lwip
        lvgl
        esp_lvgl_port
        esp_codec_dev
        esp_ringbuf
)